### ISSUE TITLE
User Story: Initial Dependencies Installation

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#10]
As a **Developer**, I want **the significant dependencies installed first** so that **I can focus on the functionalities of the site later on**.

## ACCEPTANCE CRITERIA:
- Django, gunicorn, dj_database_url, psycopg2, and dj3 cloudinary storage are all successfully installed and added to the requirements.txt.

## TASKS:
- [x] Install Django and gunicorn
- [x] Install dj_database_url and psycopg2
- [x] Install dj3-cloudinary-storage
- [x] Add the dependencies to the requirements.txt

## EPIC: #1

**Comment by marked-gil** [comment]
This user story is completed.
