### ISSUE TITLE
User Story: Basic Skeletal Structure of the Project

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#11]
As a **developer**, I can **see the basic skeletal structure of the project** .

## ACCEPTANCE CRITERIA:
- The new django project and first app are created and migrated.

## TASKS:
- [x] Create the new django project
- [x] Create initial apps - events
- [x] Add the apps to the installed apps in settings.py

## EPIC: #1

**Comment by marked-gil** [comment]
This user story is completed.

**Comment by marked-gil** [comment]
This user story is completed.
