### ISSUE TITLE
User Story: Initial Deployment to Heroku

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#12]
As a **developer**, I can **initially deploy the basic and skeletal structure of the project to Heroku** so that **I can check the initial successful connection to Heroku**.

## ACCEPTANCE CRITERIA:
- Initial deployment of the project to Heroku is successful.
- PostgreSQL and Cloudinary are set up.

## TASKS:
- [x] Create a new Heroku app
- [x] Use ElephantSQL
- [x] Create and set up the env.py
- [x] Set up the Cloudinary
- [x] Update Heroku Config vars
- [x] Update the settings.py
- [x] Create the directories: media, static, templates
- [x] Create Procfile
- [x] Deploy to Heroku

## EPIC: #2

**Comment by marked-gil** [comment]
This user story is completed.
