### ISSUE TITLE
User Story: Base Template

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#13]
As a **Developer**, I can **use a base template that contains the header with logo, navbar menu, a `block content` tag, and general footer** so that **I can connect it to other html pages**.

## ACCEPTANCE CRITERIA:
- The base template is initially set up with header.
- The base template is successfully displayed in all the other pages of the site.

## TASKS:
- [x] Create a base template.
- [x] Create a header with navbar and site name or logo
- [x] Create block tag for footer and include the general footer content

## EPIC: #4

**Comment by marked-gil** [comment]
This user story is completed.
