### ISSUE TITLE
User Story: Home Page Template

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#14]
As a **User**, I can **see the home page of the site** so that **I will know what the website is for**.

## ACCEPTANCE CRITERIA:
- **GIVEN** that the user has entered the correct base URL for the site,
**WHEN** they enter the site
**THEN** the home page will be displayed.
- The basic home page template is initially set up and linked with the base template.

## TASKS:
- [x] Create a Home page (index.html)
- [x] Connect the base template to the Home page
- [x] Include a footer at the end of the Home page template

## EPIC: #4

**Comment by marked-gil** [comment]
User story is completed.
