### ISSUE TITLE
User Story: Event Model

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#15]
As a **Developer**, I can **save new events into a database table** so that **I can use the data on the website**.

## ACCEPTANCE CRITERIA:
- The event model is constructed with fields such as title, slug, blurb, event_date, event_time, content, featured_image, author, entered_by, created_on, updated_on, likes, and etc.
- The Event model is available on the admin panel.

## TASKS:
- [x] Create an Event Model with fields such as: title, slug, blurb, event_date, event_time, content, featured_image, author, entered_by, created_on, updated_on, likes, etc.
- [x] Modify the built-in string method of Django’s base Model class
- [x] Install Summernote and use it for the post_content on Event Model
- [x] Customize the admin interface for the Event class Model
- [x] Register the Event model in admin.py

## EPIC: #3

**Comment by marked-gil** [comment]
This user story is completed.
