### ISSUE TITLE
User Story: Seating Model

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#16]
As a **developer**, I can **save the seat reservation of a signed-in member on the database** so that **I can block the specific seat/s of the event for the specific member**.

## ACCEPTANCE CRITERIA:
- The seating model is constructed with fields such as 'event', 'seat_location', 'reserved_on', and 'reserved_by'.
- The Seating model is available on the admin panel.

## TASKS:
- [x] Create Seating app
- [x] Create VenueSeat Model
- [x] Create EventSeating Model with fields such as event, seat_location, reserved_on, and reserved_by
- [x] Modify the built-in string method of Django’s base Model class
- [x] Register the VenueSeat and EventSeating models in admin.py

## EPIC: #3

**Comment by marked-gil** [comment]
This user story is complete.
