### ISSUE TITLE
User Story: Comment Model

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#17]
As a **developer**, I can **save the user’s comments into the database** so that **I can display it in its specific event post**.

## ACCEPTANCE CRITERIA:
- The comment model is constructed with fields such as text_comment, author, event_post, and posted_on.
- The Comment model is available on the admin panel

## TASKS:
- [x] Create a Comment Model with fields such as text_comment, author, event, and posted_on
- [x] Modify the built-in string method of Django’s base Model class
- [x] Register the Comment model in admin.py

## EPIC: #3

**Comment by marked-gil** [comment]
This user story is completed.
