### ISSUE TITLE
User Story: Member Registration

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#19]
As a **user**, I can **sign-up on the website** so that **I can be a member and use the full functionality of the website**.

## ACCEPTANCE CRITERIA:
- **GIVEN** that a registration template is made, 
**WHEN** it is opened
**THEN** the registration form - which includes fields for the username, first name, last name, email address, and password - shows up.
- **GIVEN** that the registration form is present,
**WHEN** the form is submitted with invalid formats on any of the fields
**THEN** the form is not submitted and a feedback message shows up.
-  **GIVEN** that the registration form is present,
**WHEN** password is created by the user
**THEN** it will be required to re-enter the same password before the form can be submitted.
- **GIVEN** that the registration form is validly completed,
**WHEN** the form is submitted,
**THEN** the user is redirected to the home page.

## TASKS:
- [x] Install django-allauth, and use its SIGN UP template
- [x] Using django-allauth, modify its default sign up form to include fields for username, first name, last name, email address, and password
- [x] Make all fields in the form required.
- [x] Prevent the submission of the form when the password is not re-entered correctly, and use django-allauth password validation to show feedback message to the user
- [x] Redirect the user to the home page when registration is validly submitted

## EPIC: #5

**Comment by marked-gil** [comment]
This user story is completed.
