### ISSUE TITLE
User Story: Sign In

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#20]
As a **user**, I can **sign in when I am registered** so that **I can access the full functionality of the website**.

## ACCEPTANCE CRITERIA:
- **GIVEN** the ‘sign in’ form is created and the user is registered,
**WHEN** the user signs in with the required valid username or email address and password
**THEN** the user can access the full functionality of the website.
- **GIVEN** the ‘sign in’ form is created,
**WHEN** the user signs in with invalid credentials
**THEN** feedback message is displayed and the form is not submitted.

## TASKS:
- [x] Modify django-allauth's 'SIGN IN' template for styling
- [x] Use django-allauth's 'SIGN IN' form that requires the user’s username and password
- [x] Redirect the user to the Home page when sign-in is successful, and flash a message to confirm that sign-in is successful.
- [x] Flash feedback message when sign-in credentials are invalid, and the URL stays the same.

## EPIC: #5

**Comment by marked-gil** [comment]
This user story is completed.
