### ISSUE TITLE
User Story: Sign Out

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#21]
As a **user**, I can **sign out after logging in** so that **I can protect my website account and prevent unauthorised persons from accessing it**.

## ACCEPTANCE CRITERIA:
- **GIVEN** the user is signed in,
**WHEN** the user clicks the sign-out button
**THEN** the user’s session is ended and access to the site is limited to its content that is for general consumption.

- **GIVEN** the user is redirected to the home page,
**WHEN** client is signed out successfully
**THEN** the user is redirected to the home page and a feedback message is shown.

## TASKS:
- [x] Create a sign-out link on the navbar
- [x] Redirect to the home page when the sign-out link is clicked
- [x] Flash a feedback message on the home page when the user is signed out successfully
- [x] Prevent users from making seat reservations, liking events, and posting comments when signed out. 

## EPIC: #5

**Comment by marked-gil** [comment]
This user story is completed.
