### ISSUE TITLE
User Story: Featured Events List

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#22]
As a **user**, I can **see the featured list of events on the home page** so that **I can immediately see the events that are coming up**.

## ACCEPTANCE CRITERIA:
- **GIVEN** home page is created,
**WHEN** the user visits the home page
**THEN** they can see a list of the featured events.

- **GIVEN** featured list of events is displayed,
**WHEN** the user clicked a featured event
**THEN** the full details of the event will be displayed on a separate page.

## TASKS:
- [x] Display the upcoming 3 - 4 events on the home page
- [x] Show title, short description, date and time
- [x] Make every featured event clickable and redirect each to their event's full detail page.

## EPIC: #6

**Comment by marked-gil** [comment]
User story completed.
