### ISSUE TITLE
User Story: All Events Page

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#23]
As a **user**, I can **See all the upcoming events** so that **I can decide which one interests me**.

## ACCEPTANCE CRITERIA:
- **GIVEN** template for all events is created,
**WHEN** user visits the ‘all events’ page
**THEN** they can browse all the upcoming events

- **GIVEN** the user is visiting the ‘all events’ page,
**WHEN** user clicks an event
**THEN** the site attempts to redirect to another page.

## TASKS:
- [x] Create a template for all the upcoming events
- [x] Display all the upcoming events in ascending order based on the date of the event
- [x] Make each event item a clickable element that redirects to another URL (to their specific event page)
- [x] Develop pagination
- [x] Redirect the 'Events' link in the navbar menu to the 'Events page'

## EPIC: #6

**Comment by marked-gil** [comment]
This user story is completed.
