### ISSUE TITLE
User Story: Specific Event’s page

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#24]
As a **user**, I can **view the full detail of the event** so that **I can learn more about the event**.

## ACCEPTANCE CRITERIA:
- **GIVEN** the user is on the home page or ‘all events’ page,
**WHEN** the user clicked an event
**THEN** the full details of the event will be displayed on a separate page.

## TASKS:
- [x] Create a template for the specific event (event's full detail page)
- [x] Display the featured banner image of the event
- [x] Display the description or writeup about the event
- [x] Display the date and time of the event
- [x] Add a ‘reserve seat’ button to the event’s page

## EPIC: #6

**Comment by marked-gil** [comment]
This user story is completed.
