### ISSUE TITLE
User Story: Event Likes

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#25]
As a **user**, I can **like an event post that interests me** so that **I can show my support for the event**.

## ACCEPTANCE CRITERIA:
- **GIVEN** the user is signed in and visiting the event’s page,
**WHEN** the user clicks the ‘like’ button
**THEN** it will add to the number of likes of the event post.

- **GIVEN** the user is signed in and visiting the event’s page,
**WHEN**  the user clicks again the ‘like’ button
**THEN** it will remove their like of the post and update the displayed number of likes of the event post.

## TASKS:
- [x] Create a ‘like’ toggle button on the specific event’s page
- [x] Display the number of likes of the event post
- [x] Add the user’s like to the total likes of the event and display it
- [x] Allow user to remove their ‘like’

## EPIC: #6

**Comment by marked-gil** [comment]
This user story is completed.
