### ISSUE TITLE
User Story: Seat Map Page

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#26]
As a **user**, I can **visit the Seat Map page** so that **I can see the seat map of the venue**.

## ACCEPTANCE CRITERIA:
- **GIVEN** the user is NOT logged in,
**WHEN** the user visits the seat map page
**THEN** the SVG seat map is displayed.

- **GIVEN**  the user is signed in,
**WHEN** the user visits the particular event's seating page
**THEN** the event’s title, date, and time are displayed, along with the event's seat map.

## TASKS
- [x] Create a generic seat map page for all users (including non-logged-in users) to visit
- [x] Create an 'Event Seating' (Seat Reservation) page/template for each specific event
- [x] Add the SVG seat map on the 'seating' pages
- [x] Allow the seat map to pan and zoom
- [x] Display the event’s title, date, time and colour legend on the 'Event Seating' page

## EPIC: #7

**Comment by marked-gil** [comment]
This user story is complete.
