### ISSUE TITLE
User Story: Restrict Seat Reservation to Signed-in Members Only

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#27]
As a **user**, I can **register as a member and sign in** so that **I can reserve seats**.

## ACCEPTANCE CRITERIA:
- **GIVEN** the user is not signed in,
**WHEN** they attempt to make a reservation by clicking the 'reserve a seat' button
**THEN** they are redirected to the sign-in page with a flash feedback message.

- **GIVEN** the un-signed-in user has been redirected to the ‘sign-in’ page,
**WHEN** the user signs in
**THEN** the user is redirected back to the Seat Reservation Page of the Event.

## TASKS:
- [x] Redirect the user to the 'Sign In' page when the un-signed-in user attempts to book a reservation
- [x] Flash a feedback message to the user to sign in when redirected to the Sign In page
- [x] Redirect the user back to the event's Seat Reservation (Event Seating) page after signing in

## EPIC: #7

**Comment by marked-gil** [comment]
This user story is completed.
