### ISSUE TITLE
User Story: Allow Seat Selection

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#28]
As a **user**, I can **select a seat** so that **I can choose the available seat I want for the event**.

## ACCEPTANCE CRITERIA:
- **GIVEN** the user is signed in,
**WHEN** I clicked on the available seat on the map
**THEN** it shows on the screen that the user has selected it.

- **GIVEN** the user has selected a seat/s,
**WHEN** the user clicks or toggles again on the selected seat/s on the seat map
**THEN** the seats are de-selected.

## TASKS:
- [x] Make all available seats on the seat map as active and can be toggled
- [x] Display all unavailable seats as inactive items on the seat map
- [x] Allow only 2 seats to be selected per member
- [x] List all selected seats on the screen
- [x] Allow de-selection of the seat

## EPIC: #7

**Comment by marked-gil** [comment]
This user story is completed.
