### ISSUE TITLE
User Story: Reservation of Selected Seats

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#29]
As a **user**, I can **reserve the selected seat/s** so that **they are saved in the database**.

## ACCEPTANCE CRITERIA:
- **GIVEN** the signed-in user has selected a seat/s,
**WHEN** they click on the ‘reserve’ button
**THEN** the seats are saved to the database and reserved.

## TASKS:
- [x] Add a ‘reserve’ button to proceed with the reservation
- [x] Save selected seats in the database
- [x] Display a flash message on the seating (seat reservation) page when a seat is successfully reserved
## EPIC: #7

**Comment by marked-gil** [comment]
This user story is completed.
