### ISSUE TITLE
User Story: Cancel and/or Update Reserved Seats

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#30]
As a **user**, I can **cancel and/or update my reserved seats** so that **other users can reserve the seats or I can conveniently change my preference**.

## ACCEPTANCE CRITERIA:
- **GIVEN** the user has already reserved a seat/s for an event,
**WHEN**  the user visits the event’s seating page
**THEN** the user's reserved seats for the event are displayed.

- **GIVEN** the user has already reserved a seat/s for an event,
**WHEN** the user clicks on the ‘Edit Seat Reservation’ button
**THEN** the reserved seats can be cancelled and/or replaced.

- **GIVEN** the signed-in user has selected a seat/s,
**WHEN** I click on the ‘cancel’ button for a reserved seat
**THEN** the selected seat/s are de-selected on the map.

- **GIVEN** the user changed their seat selection,
**WHEN** the user clicks on the ‘Update Reservation’ button
**THEN** the seat reservation is updated.

- **GIVEN** the user has cancelled all their reserved seats for the event,
**WHEN** the user clicks on the ‘Update Reservation’ button
**THEN** their reservation for the event is deleted.

## TASKS:
- [x] Add a ‘cancel’ button to remove the selected seat/s
- [x] Add an ‘Update Reservation’ button’ to allow the deletion and/or replacement of the reserved seats.
- [x] Replace the ‘Reserve’ button with 'Update Reservation' button when the user already has reserved seat/s, and show the list of reserved seats
- [x] Allow reserved seats to be cancelled or updated
- [x] When 'EventSeating' database is successfully updated, flash a feedback message

## EPIC: #7

**Comment by marked-gil** [comment]
This user story is completed.
