### ISSUE TITLE
User Story: User Comments on a Specific Event

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#31]
As a **user**, I can **leave a comment on the event page** so that **I can share my thoughts to the public about a particular event**.

## ACCEPTANCE CRITERIA:
- **GIVEN** the user is signed-in,
**WHEN** I add a comment on an event page
**THEN** it will be saved in the database.

- **GIVEN** the number of text characters for each comment is limited,
**WHEN** the user adds a comment on an event page
**THEN** the number of characters left is displayed in real-time.

- **GIVEN** the user is visiting an event's page,
**WHEN** the user scrolls down to the comment section
**THEN** they can see the comments from members.

## TASKS:
- [x] Create a form for comments on each page
- [x] Limit the comment length to 250 characters
- [x] Show realtime character counter for comments
- [x] Save the comment to the database when the ‘submit’ button is clicked
- [x] Display the comments on the event’s page along with the author's username, and time since posted

## EPIC: #8

**Comment by marked-gil** [comment]
This user story is completed.
