### ISSUE TITLE
User Story: Recycling Expired Events

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#34]
As a **site owner**, I can **set an expired event to automatically be recycled to a new scheduled date** so that **the site can perpetuate despite its contents not being monitored and updated manually**.

## ACCEPTANCE CRITERIA:
- **GIVEN** that this site is for educational purposes only and the events may not be monitored or updated regularly,
**WHEN** an event has gone past its schedule
**THEN** it will automatically be rescheduled to a future date.

- **GIVEN** that the event has gone past its schedule,
**WHEN** the event is automatically recycled with a new date
**THEN** it is re-displayed with all the other events in the order of their dates.

- **GIVEN** that the event has gone past its schedule,
**WHEN** the event is automatically recycled with a new date
**THEN** all its previously reserved seats are deleted for a new start.

## TASKS:
- [x] Automatically update the schedule of the event in the database to the following year as soon as it expires
- [x] Re-display the recycled event with the new schedule
- [x] Delete all reserved seats for the expired and recycled events

## EPIC: #9

**Comment by marked-gil** [comment]
This user story is completed.

**Comment by marked-gil** [comment]
This user story is completed
