### ISSUE TITLE
User Story: Create Member Account Page

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#36]
As a User, I can **view all of my account information/data as a registered member** so that **I can review them as needed**.

## ACCEPTANCE CRITERIA:

- **GIVEN that the user is registered and signed in to the site** ,
**WHEN I visit the Member Account Page**
**THEN I can see my username, first name, last name, email address, and seat reservations**.

## TASKS:
- [x] Create A Member Account page
- [x] In the Member Account page, display the user's username, first name, last name, and email address.
- [x] Display the user's reserved seats

## EPIC: #5

**Comment by marked-gil** [comment]
This user story is completed.
