### ISSUE TITLE
User Story: Allow Logged-in User to Edit their Account Information

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#37]
As a **User**, I can **edit my personal information/data such as first name, last name, and email address** so that **I can update them easily as necessary**.

## ACCEPTANCE CRITERIA:
- **GIVEN the user is logged in and inside the Member's Account page** ,
**WHEN I edit my personal information/data**
**THEN they are allowed to edit their provided personal information as they see fit.**

- **GIVEN the user has edited a specific personal information (eg, first name)** ,
**WHEN I click the 'Update' button**
**THEN the specific field will be updated in the database.**

## TASKS:
- [x] Make the username uneditable.
- [x] Make all input fields in the Member Account page as readonly by default.
- [x] Create edit buttons for the first name, last name, and email input fields which will enable editing of the field value.
- [x] Disable UPDATE button by default, and enable it only when changes are made in the input values.
- [x] Update the database when valid changes are made in the Member's Account form.

**Comment by marked-gil** [comment]
This user story is completed.
