### ISSUE TITLE
User Story: Allow Change of Password

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#38]
As a **User**, I can **change my password** so that **I can maintain the security of my account**.

## ACCEPTANCE CRITERIA:
- **GIVEN the user is a logged in member** ,
**WHEN they click on 'Change Password' inside the Member's Account page**
**THEN it will allow them to change their password**.

- **GIVEN the user has entered a new and verified password** ,
**WHEN they click 'save'**
**THEN the database will be updated.**

## TASKS:
- [x] Create a 'Change Password' button inside the Member's Account page
- [x] Verify the new password the user entered by asking them to re-enter the same password.
- [x] Update the database when the new password is verified and saved.

**Comment by marked-gil** [comment]
This user story is completed.
