### ISSUE TITLE
User Story: Allow Password Reset

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#39]
As a **User**, I can **reset my password** so that **I can either keep my account secured or keep using my account when I have forgotten my password**.

## ACCEPTANCE CRITERIA:
- **GIVEN that the user is logged in and has provided a valid email address** ,
**WHEN they visit the Member's Account page and click on the 'change my password' link**
**an email will be sent to the user to enable them to change his password**

- **GIVEN that the user has previously registered and has provided a valid email address** ,
**WHEN they click on 'forgot password?' link inside the Sign In page**
**THEN an email will be sent to user to enable them to change their password.**

## TASKS:
- [x] Add a 'change my password' link inside the Member's Account page and redirect it to the password reset page
- [x] Add a 'forgot my password?' link inside the Sign In page and redirect it to the password reset page
- [x] Send an email to the user with a link to allow them to change their password

**Comment by marked-gil** [comment]
This user story is completed.
