### ISSUE TITLE
User Story: Update Seat Reservation

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#40]
As a **User**, I can **update my seat reservations for an event** so that **it is convenient for changes in my preferences**.

## ACCEPTANCE CRITERIA:
- **GIVEN** the signed-in user has booked a seat/s for the event,
**WHEN** they cancel the previously booked seat,
**THEN** the user's seat reservations are updated in the database and displayed on the Event Seat page.

## TASKS:
- [x] Add a cancel button on each user's reserved seat
- [x] Update the database when a reserved seat is cancelled, and update the displayed seats
- [X] Display a flash message when the update is successful

**Comment by marked-gil** [comment]
This user story is completed.
