### ISSUE TITLE
User Story: Events Filtering

### ISSUE THREAD

**Issue by marked-gil** [marked-gil/goodwill-events#41]
As a **User**, I can **filter all the events by month** so that **it is easy and convenient for me to choose an event**.

## ACCEPTANCE CRITERIA:
- **GIVEN** that the user is on the Events page,
**WHEN** they click on the dropdown list
**THEN** the search options will be shown, which are months.

- **GIVEN**  that the user has selected an option from the dropdown list,
**WHEN** they click on the 'search' button
**THEN** the upcoming events that are scheduled for the selected month will be displayed.

- **GIVEN**  that the user has selected an option from the dropdown list,
**WHEN** no event is scheduled for the selected month,
**THEN** a feedback message stating that 'No Events Found' will be displayed.

## TASKS:
- [x] Create a form for the search/filter bar that uses `select` tag .
- [x] Add the following as options to the `select` tag: all the months of a year, and "All Events"
- [x] Create a new class for searching/filtering the events using `listview`
- [x] Display the events that are filtered or searched by the user using the filter bar
- [x] DIsplay 'No Events Found' if no events were returned from the search
- [x] Display 'Invalid query' if the search input value is not included in the options provided, such as when the user manipulates the URL in the address bar

**Comment by marked-gil** [comment]
This user story is completed.
